apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-springboot-github
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bacsumu/demo-srpingboot.git
    targetRevision: main
    path: charts/demo-springboot
  destination:
    server: https://kubernetes.default.svc
    namespace: bacsumu
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true