# aws eks에 배포 용
service:
  type: ClusterIP

image:
  pullPolicy: Always

resources:
  limits:
    cpu: 50m
  requests:
    cpu: 50m

tolerations:
- key: NodePurpose
  operator: Equal
  value: service
  effect: NoSchedule

affinity: 
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: NodePurpose
          operator: In
          values:
          - service
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - demo-springboot-github
          
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# ingress:
#  enabled: true
#  className: alb
#  annotations: 
#    kubernetes.io/ingress.class: alb
#    alb.ingress.kubernetes.io/load-balancer-name: demo_springboot_load_balancer
#    alb.ingress.kubernetes.io/subnets: 'subnet-0fbe1930b9ff77aff, subnet-0e4451d6d23d59115'
#    alb.ingress.kubernetes.io/scheme: internet-facing
#    alb.ingress.kubernetes.io/target-type: ip
#    alb.ingress.kubernetes.io/security-groups: sg-050ec948e1e43f334
#    alb.ingress.kubernetes.io/healthcheck-path: /
#    alb.ingress.kubernetes.io/healthcheck-interval-seconds: 10
#    alb.ingress.kubernetes.io/listen-ports: [{"HTTP": 80}]
#    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
#    alb.ingress.kubernetes.io/load-balancer-attributes: 'deletion_protection.enabled=false'
#  hosts:
#    - host: bacsumu.bizmsg.click
#      paths:
#      - path: /
#        pathType: Prefix