# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: 'ghcr.io/bacsumu/demo-springboot'
  TAG_NAME: 'latest'
  USERNAME: 'bacsumu'
  DEMO_REPO_TOKEN: ${{secrets.DEMO_REPO_TOKEN}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # gradle package cache 설정
    - name: cache gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle
        key: |
          ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          ${{ runner.os }}-gradle-
    # install jdk
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    # gradle build
    - name: Build with Gradle
      run: |
        pwd
        ls -l
        ./gradlew build

    # docker build
    - name: Build with Docker
      run: |
        echo $DEMO_REPO_TOKEN | docker login ghcr.io -u $USERNAME --password-stdin
        docker build --tag $REGISTRY:$TAG_NAME  -f Dockerfile .
        docker images
        docker push $REGISTRY:$TAG_NAME

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
